apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-service
  namespace: cobalt-services
  labels:
    app: core-service
    app.kubernetes.io/part-of: cobalt
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: cobalt-services
  labels:
    app: notification-service
    app.kubernetes.io/part-of: cobalt
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: violations-service
  namespace: cobalt-services
  labels:
    app: violations-service
    app.kubernetes.io/part-of: cobalt
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cobalt-frontend
  namespace: cobalt-services
  labels:
    app: frontend
    app.kubernetes.io/part-of: cobalt
automountServiceAccountToken: false
